server:
  port: 8080
spring:
  security:
    user:
      name: pp
      password: 111
      roles:
        -user

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432//findpp
    username: postgres
    password: 111
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: postgresql
    show-sql: false
#    spring.main.allow-bean-definition-overriding=true
  main:
    allow-bean-definition-overriding: true


mybatis:
  mapper-locations: classpath:/mappers/*.xml # 扫描mybatis的实现dao接口*.xml文件
  type-aliases-package: com.example.myfirstspringbootweb.entity #实体类取别名
  configuration:
    map-underscore-to-camel-case: true # 下划线转驼峰配置
